### ISSUE TITLE
【バグ】select句でカラムを絞ったときにエラーが出る

### ISSUE THREAD

**Issue by mynkit** [mynkit/connect_mysql#1]
以下のようなエラーがでた
```
Traceback (most recent call last):
  File "/Users/keitamiyano/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/connect_mysql/Connector.py", line 122, in get_query
    [list(r) for r in cur.fetchall()], columns=columns)
  File "/Users/keitamiyano/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/pandas/core/frame.py", line 435, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/Users/keitamiyano/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 404, in to_arrays
    dtype=dtype)
  File "/Users/keitamiyano/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 436, in _list_to_arrays
    coerce_float=coerce_float)
  File "/Users/keitamiyano/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 492, in _convert_object_array
    con=len(content)))
AssertionError: 41 columns passed, passed data had 7 columns
```

おそらく，'select * from table;'のつもりでしかメソッドを書いていなかったため

**Comment by mynkit** [comment]
v0.0.2で対応
